### ISSUE TITLE
Complete renaming to EventNtuple

### ISSUE THREAD

**Issue by AndrewEdmonds11** [Mu2e/EventNtuple#161]
I think we should rename the new ntuple since "TrkAna" is no longer appropriate - it is no longer one-track-per-row or an analysis framework in itself. The current candidate is EvtNtuple but we can use this issue to discuss further

**Comment by sophiemiddleton** [comment]
@AndrewEdmonds11 I think we can close this and announce the names, right?

**Comment by AndrewEdmonds11** [comment]
I think we can leave this open and use it to keep track of what needs to be renamed. Here's a current list:

- [ ] rename repo
- [ ] rename art module
- [ ] rename fcl files
- [ ] update documentation

**Comment by AndrewEdmonds11** [comment]
Done in #217
